---
output: stevetemplates::cv
geometry: margin=1in

title: "CV"
author: Thomas Arminio

jobtitle: "Program Manager"
address: "34 Congress St Trumansburg, New York"
fontawesome: yes
email: tma54@cornell.edu
# github: TMArminio
#osf: "Enter 5 digit osf string here"
phone: "+1 201 207 3327"
updated: TRUE
rdateformat: "`r format(Sys.time(), '%d %b %Y')`"

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue
---
<<<<<<< HEAD
Program manager, with big experience in inspiring large teams to execute highly-complex projects in resource-constrained environments. Possesses a depp knowledge of data analytics, management, and agriculture, acquired over eight years of sustainable agriculture practice in the United States and more than six years of global development practice in East Africa.
=======
Program manager, experienced in inspiring large teams to execute highly-complex projects in resource-constrained environments. Possesses a depp knowledge of data analytics, management, and agriculture, acquired over eight years of sustainable agriculture practice in the United States and more than five years of global development practice in East Africa.
>>>>>>> 287f41728110064dd23473e213bee6dbf7ac6297

# Experience

*One Acre Fund*
Consultant (Bahir Dar, Ethiopia) \hfill Sep 2021 - Present

Program Manager (Iringa, Tanzania) \hfill May 2018 - Aug 2021

*Peace Corps*
Crop Extension Officer (Kilimanjaro, Tanzania) \hfill Feb 2016 - Apr 2018

*Remembrance Farm*
Production Manager (Trumansburg, New York) \hfill Dec 2012 - Dec 2015

*East Hill Farm*
Founder (Rochester, New York) \hfill Jun 2008 - Dec 2012


# Education
*Cornell University*, MPA Global Development \hfill

*Seton Hall University University*, BA Literature \hfill

# Language
*Swahili*, ACTFL Oral Proficiency Interview - Advanced-High Proficiency \hfill

# Skills
Stata, R, SQL, Excel (advanced), multivariate analysis, regression analysis, Adobe Creative Cloud, Final Cut Pro, Logic Pro
